server:
  port: 9000
  servlet:
    context-path: /api

spring:
  application:
   name: "webapp"

  datasource:
    url: jdbc:mysql://localhost:3306/webappcommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: "org.hibernate.dialect.MySQL8Dialect"

      hibernate:
        use-new-id-generator-mappings: false
        naming:
          physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        ddl-auto: "create-drop"